sudo: required
dist: trusty

os: linux

language: c

compiler:
    - gcc

env:
    matrix:
        - NGINX_VERSION=1.12.0

install:
    - sudo apt-get install -qq -y cpanminus libluajit-5.1-dev libgd-dev
    - sudo cpanm -v --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
    - wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && tar -xzf nginx-${NGINX_VERSION}.tar.gz

script:
    - cd nginx-${NGINX_VERSION}/
    - ./configure --with-debug --add-module=.. > build.log 2&>1 || (cat build.log && exit 1)
    - make -j2 > build.log 2&>1 || (cat build.log && exit 1)
    - export PATH=$PATH:`pwd`/objs
    - cd ..
    - prove -r t/
